name: MbPets
version: 2.2
main: io.github.apfelcreme.MbPets.MbPets
depend: [LibsDisguises, UUIDDB]
softdepend: [AnimalProtect, Vault]

commands:
   pet:
      description: All pet related things.
      usage: 
      permission: 
      permission-message:
            
permissions: 
  MbPets.*:
    description: All
    children: 
      MbPets.user: true
      MbPets.moderator: true
  MbPets.user:
    description: buy, call, modify, convert usw. 
    children:
      MbPets.call: true
      MbPets.buy: true
      MbPets.confirm: true
      MbPets.modify: true
      MbPets.convert: true
      MbPets.print: true
      MbPets.sell: true
  MbPets.moderator:
    description: unregister, monitor, reload, regenerate, despawn
    children:
      MbPets.user: true
      MbPets.delete: true
      MbPets.monitor: true
      MbPets.reload: true
      MbPets.regenerate: true
      MbPets.despawn: true
  MbPets.call:
    description: call & uncall pets
  MbPets.buy:
    description: buy & confirm pets
  MbPets.sell:
    description: sell pets
  MbPets.modify:
    description: modify pets
  MbPets.convert:
    description: convert animals to pets
  MbPets.print:
    description: print stuff
  MbPets.delete:
    description: delete pets
  MbPets.despawn:
    description: despawn all currently called pets
  MbPets.monitor:
    description: monitor some stuff
  MbPets.reload:
    description: reload config
  MbPets.regenerate:
    description: regenerate config